//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckDetail
    {
        public int PaymentId { get; set; }
        public string AccountOwnerName { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> BankId { get; set; }
        public string BranchName { get; set; }
        public Nullable<int> BranchNumber { get; set; }
        public Nullable<System.DateTime> RepaymentDate { get; set; }
        public Nullable<int> Sum { get; set; }
        public string Comments { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
