//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Child(string IdentityNum,int FamilyId,string FirstName,bool? Kind,DateTime? BirthDate,int? PlaceInFamily,int? SchoolId,
            int? Grade,DateTime? JoiningDate,bool ViturSodiutFrom,string PreviousCare,string Note,bool IsActive,bool? IsMunicipality,
          int? sumAfterDiscount)
        {
            this.IdentityNum = IdentityNum;
            this.FamilyId = FamilyId;
            this.FirstName = FirstName;
            this.Kind = Kind;
            this.BirthDate = BirthDate;
            this.PlaceInFamily = PlaceInFamily;
            this.SchoolId = SchoolId;
            this.Grade = Grade;
            this.JoiningDate = JoiningDate;
            this.ViturSodiutFrom = ViturSodiutFrom;
            this.PreviousCare = PreviousCare;
            this.Note = Note;
            this.IsActive = IsActive;
            this.IsMunicipality = IsMunicipality;
            this.sumAfterDiscount = sumAfterDiscount;
        }
        public Child()
        {
            this.ChildsRegistrationToSubjects = new HashSet<ChildsRegistrationToSubject>();
            this.Groups = new HashSet<Group>();
            this.Lessons = new HashSet<Lesson>();
            this.Payments = new HashSet<Payment>();
            this.TammyValues = new HashSet<TammyValue>();
        }
    
        public string IdentityNum { get; set; }
        public int FamilyId { get; set; }
        public string FirstName { get; set; }
        public Nullable<bool> Kind { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> PlaceInFamily { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public bool ViturSodiutFrom { get; set; }
        public string PreviousCare { get; set; }
        public string Note { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsMunicipality { get; set; }
        public Nullable<int> sumAfterDiscount { get; set; }
    
        public virtual Family Family { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChildsRegistrationToSubject> ChildsRegistrationToSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Group> Groups { get; set; }
        public virtual School School { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lesson> Lessons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TammyValue> TammyValues { get; set; }
    }
}
