//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildsRegistrationToSubject
    {
        public Nullable<int> SubjectId { get; set; }
        public string ChildId { get; set; }
        public int Id { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<bool> WaitMode { get; set; }
        public string Comments { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
