//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditDetail
    {
        public string CreditDetailsId { get; set; }
        public int PaymentId { get; set; }
        public string PayerName { get; set; }
        public string OwnerName { get; set; }
        public string OwnerIdentityNumber { get; set; }
        public string CreditNumber { get; set; }
        public string CardExpirationDate { get; set; }
        public string ThreeLastDigits { get; set; }
        public Nullable<int> NumberOfPayments { get; set; }
        public Nullable<System.DateTime> FirstRepaymentDate { get; set; }
        public string Comments { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
