//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Family()
        {
            this.Childs = new HashSet<Child>();
        }
    
        public int FamilyId { get; set; }
        public string FamilyName { get; set; }
        public string FatherFirstName { get; set; }
        public string MotherFirstName { get; set; }
        public Nullable<int> NumOfChildren { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string Cellular1 { get; set; }
        public string Cellular2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Child> Childs { get; set; }
        public virtual City City { get; set; }
    }
}
