//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ChildId { get; set; }
        public System.TimeSpan StartsAt { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> Subject { get; set; }
        public Nullable<double> LessonDuration { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> Day { get; set; }
    
        public virtual Child Child { get; set; }
        public virtual Group Group { get; set; }
        public virtual Subject Subject1 { get; set; }
    }
}
