//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.WorkingDays = new HashSet<WorkingDay>();
        }
    
        public string IdentityNum { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Kind { get; set; }
        public Nullable<int> DutyCode { get; set; }
        public string Tel { get; set; }
        public string CellPhone { get; set; }
        public Nullable<int> City { get; set; }
        public string Street { get; set; }
        public Nullable<int> HouseNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Type { get; set; }
        public int Id { get; set; }
        public Nullable<int> RateForFirstYear { get; set; }
        public Nullable<int> RateForNextYear { get; set; }
    
        public virtual City City1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkingDay> WorkingDays { get; set; }
    }
}
