//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssistanceMeeting
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public string ShortDescription { get; set; }
        public string Content { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> StudentId_1 { get; set; }
        public Nullable<int> StudentId_2 { get; set; }
        public Nullable<int> DurationInMinutes { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public string שדה1 { get; set; }
        public Nullable<int> AssistanceId { get; set; }
    
        public virtual Assistance Assistance { get; set; }
    }
}
